### ISSUE TITLE
Help to fix build process

### ISSUE THREAD

**Issue by slaterx** [Uninen/SVGeneration#1]
Hi!

I would like to help in fixing the build process.

Could you please explain what's happening, what's the current error and the process?

I'll create a PR fixing it.

Thanks!

**Comment by Uninen** [comment]
Don't have the cycles to set this up again (migrated to a new machine since the last build) but if you install the npm packages and try to run the grunt commands, you'll spot the errors. (Note that I hard-coded some of the paths in the gruntfile to get it working.)

The optimal solution would probably be to migrate from legacy grunt to new webpack instead but any working solution would be a step forward :)
